configfile: "config/config.yaml"

include: "rules/qc.smk"
include: "rules/compensate.smk"
include: "rules/gate.smk"
include: "rules/report.smk"

rule all:
    input:
        expand("reports/{sample}_qc_report.html", sample=config["samples"])