configfile: "config/config.yaml"

include: "rules/qc.smk"
include: "rules/compensate.smk"
include: "rules/gate.smk"
include: "rules/report.smk"
include: "rules/upload.smk"

rule all:
    input:
        expand("reports/{sample}_upload.done", sample=config["samples"])